[workspace]
resolver = "2"
members = ["safehouse-render", "safehouse-gpu", "slicebytes", "pong", "safehouse-data"]
exclude = ["safehouse"]

[workspace.dependencies]
winit = "0.29"
wgpu = { version = "0.19" }
obj-rs = {git = "https://github.com/simnalamburt/obj-rs.git", branch = "main"}
safehouse-gpu ={ path = "safehouse-gpu" }
#safehouse-debug ={ path = "safehouse-debug" }
safehouse-render ={ path = "safehouse-render" }
safehouse-data ={ path = "safehouse-data" }
futures = "*"
image = {version = "0.25.1", features = ["jpeg","png"]}
#imgui = { git = "https://github.com/imgui-rs/imgui-rs.git", rev="cd97e17" }
#imgui-winit-support = { git = "https://github.com/imgui-rs/imgui-rs.git", rev="cd97e17" }
#imgui-wgpu = { path = "./imgui-wgpu-rs"}
slicebytes = { path = "./slicebytes" }
