[workspace]
resolver = "2"
members = ["safehouse", "safehouse-debug"]

[workspace.dependencies]
# glium = "0.32.1"
glium = {git = "https://github.com/glium/glium.git", features = ["simple_window_builder", "winit"]}
glutin-winit = "0.4"
winit = "0.29"
raw-window-handle = "0.5"