[package]
name = "walk-demo-engine"
version = "0.1.0"
edition = "2021"

[dependencies]
safehouse-render = {workspace = true, features = ["text"]}
winit-app-handler = {workspace = true}

[build-dependencies]
safehouse-data = {workspace = true}