[package]
name = "safehouse-debug"
version = "0.1.0"
edition = "2021"

[dependencies]
safehouse-render = {workspace = true}
imgui-wgpu = {git = "https://github.com/Yatekii/imgui-wgpu-rs.git"}
imgui = "*"
imgui-winit-support = "*"